parameters:
  memcached_client_host: 'localhost'
  memcached_client_port: 11211

services:
  cache_key_generator:
    class: '\Picamator\CacheManager\Cache\KeyGenerator'

  object_manager:
    class: '\Picamator\CacheManager\ObjectManager'

  cache_item_factory:
    class: '\Picamator\CacheManager\Cache\CacheItemFactory'
    arguments: ['@object_manager']

  search_result_factory:
    class: '\Picamator\CacheManager\Data\SearchResultFactory'
    arguments: ['@object_manager']

  search_criteria_builder:
    class: '\Picamator\CacheManager\Data\SearchCriteriaBuilder'
    arguments: ['@object_manager']

  memcached_client:
    class: '\Memcached'
    calls:
      - ['addServer', ['%memcached_client_host%', '%memcached_client_port%']]

  cache_item_pool:
    class: '\Cache\Adapter\Memcached\MemcachedCachePool'
    arguments: ['@memcached_client']

  # operations, SHOULD be lazy loaded because it might be highly possible that CacheManager was created only to use one or two operations
  operation_save:
    class: '\Picamator\CacheManager\Operation\Save'
    arguments: ['@cache_key_generator', '@cache_item_pool', '@cache_item_factory']
    lazy: true

  operation_search:
    class: '\Picamator\CacheManager\Operation\Search'
    arguments: ['@cache_key_generator', '@cache_item_pool', '@search_result_factory']
    lazy: true

  operation_delete:
    class: '\Picamator\CacheManager\Operation\Delete'
    arguments: ['@cache_key_generator', '@cache_item_pool']
    lazy: true

  # logger: info
  logger_stream_handler:
    class: '\Monolog\Handler\StreamHandler'
    arguments: ['./../../../../data/log/app.log', 200]

  logger:
    class: '\Monolog\Logger'
    arguments: ['name']
    calls:
      - ['pushHandler', ['%logger_stream_handler%']]

  # main
  cache_manager:
    class: '\Picamator\CacheManager\CacheManager'
    arguments: ['@operation_save', '@operation_search', '@operation_delete']

  cache_manager_subject:
    class: '\Picamator\CacheManager\CacheManagerSubject'
    arguments: ['@cache_manager']
